/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.patent.action.user;

import java.io.PrintWriter;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.alibaba.fastjson.JSON;
import com.patent.action.base.Transcode;
import com.patent.factory.AppFactory;
import com.patent.module.ApplyInfoTb;
import com.patent.module.CpyInfoTb;
import com.patent.module.CpyUserInfo;
import com.patent.module.SuperUser;
import com.patent.page.PageConst;
import com.patent.service.ApplyInfoManager;
import com.patent.service.CpyInfoManager;
import com.patent.service.CpyRoleInfoManager;
import com.patent.service.CpyUserInfoManager;
import com.patent.service.SuperUserManager;
import com.patent.tools.Convert;
import com.patent.tools.MD5;
import com.patent.util.Constants;

/** 
 * MyEclipse Struts
 * Creation date: 07-29-2018
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class UserAction extends DispatchAction {
	
	/**
	 * 获取session中的用户ID
	 * @param request
	 * @return
	 */
	private Integer getLoginUserId(HttpServletRequest request){
        Integer userId = (Integer)request.getSession(false).getAttribute(Constants.LOGIN_USER_ID);
        return userId;
	}

	/**
	 * 获取session中的用户角色编号
	 * @param request
	 * @return
	 */
	private Integer getLoginRoleId(HttpServletRequest request){
        Integer userId = (Integer)request.getSession(false).getAttribute(Constants.LOGIN_USER_ROLE_ID);
        return userId;
	}
	
	/**
	 * 获取session中的用户角色名称
	 * @param request
	 * @return
	 */
	private String getLoginRoleName(HttpServletRequest request){
        String roleName = (String)request.getSession(false).getAttribute(Constants.LOGIN_USER_ROLE_NAME);
        return roleName;
	}
	
	/**
	 * 获取session中的登录类型
	 * @author Administrator
	 * @date 2018-7-31 下午09:39:57
	 * @ModifiedBy
	 * @param request
	 * @return
	 */
	private String getLoginType(HttpServletRequest request){
        String loginType = (String)request.getSession(false).getAttribute(Constants.LOGIN_TYPE);
        return loginType;
	}
	/**
	 * 获取个人用户详细记录
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception 
	 */
	public ActionForward getUserDetail(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		// TODO Auto-generated method stub
		Integer userId = this.getLoginUserId(request);
		String loginType = this.getLoginType(request);
		CpyUserInfoManager cum = (CpyUserInfoManager) AppFactory.instance(null).getApp(Constants.WEB_CPY_USER_INFO); 
		ApplyInfoManager am = (ApplyInfoManager) AppFactory.instance(null).getApp(Constants.WEB_APPLY_INFO);
		SuperUserManager sum = (SuperUserManager)  AppFactory.instance(null).getApp(Constants.WEB_SUPER_USER_INFO);
		Map<String,Object> map = new HashMap<String,Object>();
		if(loginType.equals("appUser")){//申请人/公司身份
			ApplyInfoTb appUser = am.getEntityById(userId);
			if(appUser != null){
				map.put("result", "success");
				map.put("id", appUser.getId());
				map.put("name", appUser.getAppName());
				map.put("type", appUser.getAppType());
				map.put("appICard", appUser.getAppICard());
				map.put("appAddress", appUser.getAppAddress());
				map.put("appAccount", appUser.getAppAccount());
				map.put("appLxr", appUser.getAppLxr());
				map.put("tel", appUser.getAppTel());
				map.put("email", appUser.getAppEmail());
			}else{
				map.put("result", "noUser");//查无此人
			}
		}else if(loginType.equals("cpyUser")){//代理机构
			CpyUserInfo cpyUser = cum.getEntityById(userId);
			if(cpyUser != null){
				map.put("result", "success");
				map.put("id", cpyUser.getId());
				map.put("name", cpyUser.getUserName());
				map.put("account", cpyUser.getUserAccount());
				map.put("sex", cpyUser.getUserSex());
				map.put("email", cpyUser.getUserEmail());
				map.put("tel", cpyUser.getUserTel());
				map.put("inDate", cpyUser.getUserInDate());
				map.put("outDate", cpyUser.getUserOutDate());
				map.put("lzStatus", cpyUser.getUserLzStatus());
				map.put("zxNum", cpyUser.getUserZxNum());
				map.put("scFiled", cpyUser.getUserScFiledId());
				map.put("scFiledName", cpyUser.getUserScFiledName());
				map.put("useExp", cpyUser.getUserExper());
			}else{
				map.put("result", "noUser");//查无此人
			}
		}else if(loginType.equals("spUser")){//平台用户
			List<SuperUser> suList = sum.listInfoById(userId);
			if(suList.size() > 0){
				SuperUser spUser = suList.get(0);
				map.put("result", "success");
				map.put("id", spUser.getId());
				map.put("name", spUser.getUserName());
				map.put("account", spUser.getAccount());
				map.put("type", spUser.getUserType());
			}else{
				map.put("result", "noUser");//查无此人
			}
		}else{
			map.put("result", "fail");//session失效或者捣乱
		}
		String json = JSON.toJSONString(map);
        PrintWriter pw = response.getWriter();  
        pw.write(json); 
        pw.flush();  
        pw.close();
		return null;
	}
	
	/**
	 * 修改个人基本信息(代理机构和申请人/公司用)
	 * @description
	 * @author wm
	 * @date 2018-8-3 上午11:13:55
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward updateUserDetail(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		// TODO Auto-generated method stub
		Integer userId = this.getLoginUserId(request);
		String loginType = this.getLoginType(request);
		CpyUserInfoManager cum = (CpyUserInfoManager) AppFactory.instance(null).getApp(Constants.WEB_CPY_USER_INFO); 
		ApplyInfoManager am = (ApplyInfoManager) AppFactory.instance(null).getApp(Constants.WEB_APPLY_INFO);
		boolean flag = false;
		Map<String,Boolean> map = new HashMap<String,Boolean>();
		if(loginType.equals("appUser")){//申请人/公司身份
			String appiCard = request.getParameter("appiCard");
			String address = Transcode.unescape(request.getParameter("address"), request);
			String lxr = Transcode.unescape(request.getParameter("lxr"), request);
			String tel = request.getParameter("tel");
			String email = request.getParameter("email");
			String qq = request.getParameter("qq");
			flag = am.updateUserDetailById(userId, appiCard, address, lxr, tel, email, qq);
		}else if(loginType.equals("cpyUser")){//代理机构
			String userName = Transcode.unescape(request.getParameter("name"), request);
			String userNamePy =  Convert.getFirstSpell(userName);
			String userSex = request.getParameter("sex");
			String userEmail = request.getParameter("email");
			String userTel = request.getParameter("tel");
			flag = cum.updateBasicInfoById(userId, userName, userNamePy, userSex, userEmail, userTel);
			if(flag){
				String userScFiledIdStr = request.getParameter("userScFiledIdStr");
				String userScFiledNameStr = Transcode.unescape(request.getParameter("userScFiledNameStr"), request);
				flag = cum.updateInfoById(userId, 0, userScFiledIdStr, userScFiledNameStr, 0);
			}
		}else{
			
		}
		map.put("result", flag);
		String json = JSON.toJSONString(map);
        PrintWriter pw = response.getWriter();  
        pw.write(json); 
        pw.flush();  
        pw.close();
		return null;
	}
	
	/**
	 * 修改用户密码
	 * @author Administrator
	 * @date 2018-7-31 下午09:37:46
	 * @ModifiedBy
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward updateUserPass(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		// TODO Auto-generated method stub
		Integer userId = this.getLoginUserId(request);
		String loginType = this.getLoginType(request);
		CpyUserInfoManager cum = (CpyUserInfoManager) AppFactory.instance(null).getApp(Constants.WEB_CPY_USER_INFO); 
		ApplyInfoManager am = (ApplyInfoManager) AppFactory.instance(null).getApp(Constants.WEB_APPLY_INFO);
		SuperUserManager sum = (SuperUserManager)  AppFactory.instance(null).getApp(Constants.WEB_SUPER_USER_INFO);
		Map<String,String> map = new HashMap<String,String>();
		String inputPass_old = String.valueOf(request.getParameter("passOld"));
		String newPass = String.valueOf(request.getParameter("newPass"));
		MD5 md5 = new MD5();
		String msg = "";
		if(inputPass_old.equals("null") || inputPass_old.equals("")){
			msg = "oldNull";//输入原数据库密码为空
		}else{
			if(loginType.equals("cpyUser")){
				CpyUserInfo cUser = cum.getEntityById(userId);
				if(cUser != null){
					String pass_db = cUser.getUserPassword();
					if(pass_db.equalsIgnoreCase(md5.calcMD5(inputPass_old))){
						cum.updatePassById(userId, newPass);
						msg = "success";
					}else{
						msg = "noMatch";//不匹配
					}
				}
			}else if(loginType.equals("appUser")){
				ApplyInfoTb app = am.getEntityById(userId);
				if(app != null){
					String pass_db = app.getAppPass();
					if(pass_db.equalsIgnoreCase(md5.calcMD5(inputPass_old))){
						am.updatePassById(userId, newPass);
						msg = "success";
					}else{
						msg = "noMatch";//不匹配
					}
				}
			}else if(loginType.equals("spUser")){
				List<SuperUser> suList = sum.listInfoById(userId);
				if(suList.size() > 0){
					String pass_db = suList.get(0).getPassword();
					if(pass_db.equalsIgnoreCase(md5.calcMD5(inputPass_old))){
						sum.updateSUserById(userId, newPass, "");
						msg = "success";
					}else{
						msg = "noMatch";//不匹配
					}
				}
			}
		}
		map.put("result", msg);
		String json = JSON.toJSONString(map);
        PrintWriter pw = response.getWriter();  
        pw.write(json); 
        pw.flush();  
        pw.close();
		return null;
	}
	
	/**
	 * 获取用户所在的代理机构信息
	 * @description
	 * @author wm
	 * @date 2018-8-2 上午08:37:49
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward getCpyDetailInfo(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		// TODO Auto-generated method stub
		Integer userId = this.getLoginUserId(request);
		CpyUserInfoManager cum = (CpyUserInfoManager) AppFactory.instance(null).getApp(Constants.WEB_CPY_USER_INFO); 
		CpyUserInfo cpyUser = cum.getEntityById(userId);
		Map<String,Object> map = new HashMap<String,Object>();
		if(cpyUser != null){
			CpyInfoTb cpy = cpyUser.getCpyInfoTb();
			map.put("result", "success");
			map.put("cpyId", cpy.getId());
			map.put("cpyName", cpy.getCpyName());
			map.put("cpyProv", cpy.getCpyProv());
			map.put("cpyCity", cpy.getCpyCity());
			map.put("cpyAddress", cpy.getCpyAddress());
			map.put("cpyFr", cpy.getCpyFr());
			map.put("cpyYyzz", cpy.getCpyYyzz());
			map.put("cpyLxr", cpy.getCpyLxr());
			map.put("lxrTel", cpy.getLxrTel());
			map.put("lxrEmail", cpy.getLxrEmail());
			map.put("cpyUrl", cpy.getCpyUrl());
			map.put("cpyProfile", cpy.getCpyProfile());
			map.put("signDate", cpy.getSignDate());
			map.put("endDate", cpy.getEndDate());
			map.put("hotStatus", cpy.getHotStatus());
			Integer cpyLevel = cpy.getCpyLevel();
			String cpyLevelChi = "铁牌";
			if(cpyLevel.equals(1)){
				cpyLevelChi = "铜牌";
			}else if(cpyLevel.equals(1)){
				cpyLevelChi = "银牌";
			}else if(cpyLevel.equals(1)){
				cpyLevelChi = "金牌";
			}else if(cpyLevel.equals(1)){
				cpyLevelChi = "钻石";
			}
			map.put("cpyLevel", cpyLevelChi);
		}else{
			map.put("result", "error");
		}
		String json = JSON.toJSONString(map);
        PrintWriter pw = response.getWriter();  
        pw.write(json); 
        pw.flush();  
        pw.close();
		return null;
	}
	
	/**
	 * 修改代理机构基本信息
	 * @description
	 * @author wm
	 * @date 2018-8-2 上午09:02:58
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward updateCpylInfo(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		CpyUserInfoManager cum = (CpyUserInfoManager) AppFactory.instance(null).getApp(Constants.WEB_CPY_USER_INFO); 
		CpyInfoManager cm = (CpyInfoManager) AppFactory.instance(null).getApp(Constants.WEB_CPY_INFO); 
		Map<String,String> map = new HashMap<String,String>();
		String roleName = this.getLoginRoleName(request);
		String msg = "";
		if(roleName.equals("管理员")){//只有管理员才能修改
			CpyUserInfo cpyUser = cum.getEntityById(this.getLoginUserId(request));
			if(cpyUser != null){
				Integer cpyId = cpyUser.getCpyInfoTb().getId();
				if(cpyId > 0){
					String cpyName = Transcode.unescape(request.getParameter("cpyName"), request);
					String cpyProv = Transcode.unescape(request.getParameter("cpyProv"), request);
					String cpyCity = Transcode.unescape(request.getParameter("cpyCity"), request);
					String cpyAddress = Transcode.unescape(request.getParameter("cpyAddress"), request);
					String cpyFr = Transcode.unescape(request.getParameter("cpyFr"), request);
					String cpyYyzz = Transcode.unescape(request.getParameter("cpyYyzz"), request);
					String cpyLxr = Transcode.unescape(request.getParameter("cpyLxr"), request);
					String lxrTel = Transcode.unescape(request.getParameter("lxrTel"), request);
					String lxrEmail = Transcode.unescape(request.getParameter("lxrEmail"), request);
					String cpyUrl = Transcode.unescape(request.getParameter("cpyUrl"), request);
					String cpyProfile = Transcode.unescape(request.getParameter("cpyProfile"), request);
					boolean flag = cm.updateBasicCpyInfoById(cpyId, cpyName,cpyAddress, cpyProv, cpyCity, cpyFr, cpyLxr, lxrTel, lxrEmail, cpyYyzz,cpyUrl, cpyProfile);
					if(flag){
						msg = "success";
					}else{
						msg = "error";
					}
				}
			}
		}else{
			msg = "noAbility";//没有权限
		}
		map.put("result", msg);
		String json = JSON.toJSONString(map);
        PrintWriter pw = response.getWriter();  
        pw.write(json); 
        pw.flush();  
        pw.close();
		return null;
	}

	/**
	 * 管理员增加代理机构员工
	 * @author Administrator
	 * @date 2018-8-3 下午10:45:42
	 * @ModifiedBy
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward addCpyUserInfo(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		CpyUserInfoManager cum = (CpyUserInfoManager) AppFactory.instance(null).getApp(Constants.WEB_CPY_USER_INFO);
		CpyRoleInfoManager crm = (CpyRoleInfoManager) AppFactory.instance(null).getApp(Constants.WEB_CPY_ROLE_INFO);
		String roleName = this.getLoginRoleName(request);
		Integer userId = this.getLoginUserId(request);
		CpyUserInfo cUser = cum.getEntityById(userId);
		Integer cpyId = 0;
		String msg = "";
		if(cUser != null){
			cpyId = cUser.getCpyInfoTb().getId();
			if(roleName.equals("管理员")){//只有管理员才能增加
				String userName = Transcode.unescape(request.getParameter("name"), request);
				String userNamePy =  Convert.getFirstSpell(userName);
				String account = request.getParameter("account");
				String userSex = request.getParameter("sex");
				String userEmail = request.getParameter("email");
				String userTel = request.getParameter("tel");
				String inDate = request.getParameter("inDate");
				String userScFiledIdStr = request.getParameter("userScFiledIdStr");
				String userScFiledNameStr = Transcode.unescape(request.getParameter("userScFiledNameStr"), request);
				Integer roleId = Integer.parseInt(request.getParameter("roleId"));
				Integer cpyUserId = cum.addCpyUser(cpyId, userName, userNamePy, account, new MD5().calcMD5("123456"), userSex, 
						userEmail, userTel, inDate, userScFiledIdStr, userScFiledNameStr);
				if(cpyUserId > 0){
					//绑定员工角色
					Integer cruId = crm.addRoleUser(roleId, cpyUserId);
					if(cruId > 0){
						msg = "success";
					}else{
						msg = "error";
					}
				}else{
					msg = "error";	
				}
			}else{
				msg = "noAbility";
			}
		}else{
			msg = "fail";
		}
		Map<String,String> map = new HashMap<String,String>();
		map.put("result", msg);
		String json = JSON.toJSONString(map);
        PrintWriter pw = response.getWriter();  
        pw.write(json); 
        pw.flush();  
        pw.close();
		return null;
	}
	
	/**
	 * 根据条件分页获取当前代理机构的所有用户列表
	 * @author Administrator
	 * @date 2018-8-3 下午11:09:41
	 * @ModifiedBy
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward getCpyUserPageInfo(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		CpyUserInfoManager cum = (CpyUserInfoManager) AppFactory.instance(null).getApp(Constants.WEB_CPY_USER_INFO);
		Integer currLoginUserId = this.getLoginUserId(request);
		CpyUserInfo cUser = cum.getEntityById(currLoginUserId);
		Integer cpyId = 0;
		if(cUser != null){
			cpyId = cUser.getCpyInfoTb().getId();
			Integer userLzStatus = Integer.parseInt(request.getParameter("userLzStatus"));
			Integer userYxStatus = Integer.parseInt(request.getParameter("userYxStatus"));
			Integer roleId = Integer.parseInt(request.getParameter("roleId"));
			String userNamePy = request.getParameter("userNamePy");
			Integer count = cum.getCountByOpt(cpyId, userLzStatus, userYxStatus, roleId, userNamePy);
			if(count > 0){
				Integer pageSize = PageConst.getPageSize(String.valueOf(request.getParameter("pageSize")), 10);
				Integer pageCount = PageConst.getPageCount(count, pageSize);
				Integer pageNo = PageConst.getPageNo(String.valueOf(request.getParameter("pageNo")), pageCount);
				List<CpyUserInfo> cUserList = cum.listPageInfoByOpt(cpyId, userLzStatus, userYxStatus, roleId, userNamePy, pageNo, pageSize);
				Map<String,Object> map = new HashMap<String,Object>();
				
			}
		}
		
		return null;
	}
	
	/**
	 * 根据条件获取当前代理机构的所有用户记录条数
	 * @author Administrator
	 * @date 2018-8-3 下午11:10:41
	 * @ModifiedBy
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward getCpyUserCount(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		CpyUserInfoManager cum = (CpyUserInfoManager) AppFactory.instance(null).getApp(Constants.WEB_CPY_USER_INFO);
		Integer currLoginUserId = this.getLoginUserId(request);
		CpyUserInfo cUser = cum.getEntityById(currLoginUserId);
		Integer cpyId = 0;
		Integer count = 0;
		Map<String,Integer> map = new HashMap<String,Integer>();
		if(cUser != null){
			cpyId = cUser.getCpyInfoTb().getId();
			Integer userLzStatus = Integer.parseInt(request.getParameter("userLzStatus"));
			Integer userYxStatus = Integer.parseInt(request.getParameter("userYxStatus"));
			Integer roleId = Integer.parseInt(request.getParameter("roleId"));
			String userNamePy = request.getParameter("userNamePy");
			count = cum.getCountByOpt(cpyId, userLzStatus, userYxStatus, roleId, userNamePy);
		}
		map.put("result", count);
		String json = JSON.toJSONString(map);
        PrintWriter pw = response.getWriter();  
        pw.write(json); 
        pw.flush();  
        pw.close();
		return null;
	}
}